# Generated by Django 4.0.1 on 2022-03-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=50)),
                ('url_image', models.ImageField(blank=True, default='', null=True, upload_to='img/')),
            ],
            options={
                'db_table': 'profiles',
                'managed': True,
            },
        ),
    ]
