# Generated by Django 4.0.1 on 2022-03-02 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='tablaprofile',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tablaprofile',
            name='url_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img-profile/'),
        ),
        migrations.AlterModelTable(
            name='tablaprofile',
            table='tabla_profiles',
        ),
    ]
