# Generated by Django 4.0.1 on 2022-01-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_alter_primertabla_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primertabla',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
