# Generated by Django 4.0.1 on 2022-02-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoadImage', '0004_alter_tablaarchivos_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaarchivos',
            name='url_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/'),
        ),
    ]
