# Generated by Django 4.0.1 on 2022-01-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegundaTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=50)),
                ('numero', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank='', default='', upload_to='imagenes/')),
            ],
            options={
                'db_table': 'usuarios_datos',
                'managed': True,
            },
        ),
    ]
